apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  type: ClusterIP
  ports:
    - port: 3306                # Port on the service (frontend port)
      targetPort: vprodb-port   # Port on the Pod
      protocol: TCP
  selector:
    app: vprodb          # Label selector to match Pods