apiVersion: v1
kind: Service
metadata:
  name: vprochache01
spec:
  type: ClusterIP
  ports:
    - port: 11211                # Port on the service (frontend port)
      targetPort: vpromc-port    # Port on the Pod
      protocol: TCP
  selector:
    app: vpromc          # Label selector to match Pods