apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  type: ClusterIP
  ports:
    - port: 15672                  # Port on the service (frontend port)
      targetPort: vpromq01-port    # Port on the Pod
      protocol: TCP
  selector:
    app: vpromq01          # Label selector to match Pods