apiVersion: v1
kind: Service
metadata:
  name: vprochache01
spec:
  type: LoadBalancer
  ports:
    - port: 80                    # Port on the service (frontend port)
      targetPort: vproapp-port    # Port on the Pod
      protocol: TCP
  selector:
    app: vproapp          # Label selector to match Pods